name: Issue Opened Workflow

on:
  issues:
    types:
      - opened

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute PHP Script
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          AUTHOR_USERNAME: ${{ github.event.issue.user.login }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TOKEN: ${{ secrets.ISSUE_TOKEN }}
          ISSUE_NO: ${{ github.event.issue.number }}
        run: php newissue.php
      
      - name: Commit and Push Changes
        run: |
          git config user.name "Avadhesh18"
          git config user.email "avadhesh18@users.noreply.github.com"
          git add docs/tests  
          git commit -m "Update pages"
          git push
